on:
  push:
    branches:
      - '**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          REPO: ${{ github.repository }}
          ACTOR: ${{ github.actor }}
          BRANCH: ${{ github.ref_name }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          jq -n --arg repo "$REPO" \
                --arg actor "$ACTOR" \
                --arg branch "$BRANCH" \
                --arg url "$COMMIT_URL" \
                --arg message "$COMMIT_MESSAGE" \
                '{
                  content: "@everyone Repository Update:",
                  embeds: [{
                    title: $repo,
                    description: "**\($actor)** pushed to `\($branch)`\n[View Commit](\($url))\n\n```\n\($message)\n```",
                    color: 16776960,
                    author: {
                      name: $actor,
                      url: "https://github.com/\($actor)",
                      icon_url: "https://github.com/\($actor).png"
                    }
                  }]
                }' > payload.json

          curl -H "Content-Type: application/json" \
               -X POST \
               -d @payload.json \
               "$DISCORD_WEBHOOK"
